import = [
    "~/.config/alacritty/themes/themes/monokai.toml"
]

[font]
normal = { family = "Hack Nerd Font" }
size = 17

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[window]
dynamic_title = true
dynamic_padding = true
decorations_theme_variant = "Dark"
