tap "eugenmayer/dockersync"
tap "hashicorp/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
brew "bash"
brew "node@14"
brew "code-server"
brew "fish"
brew "fzf"
brew "gh"
brew "ghq"
brew "go"
brew "hub"
brew "jq"
brew "libpq"
brew "luv"
brew "mas"
brew "minikube"
brew "mysql"
brew "neovim"
brew "peco"
brew "postgresql"
brew "pstree"
brew "socat"
brew "spotify-tui"
brew "tflint"
brew "the_silver_searcher"
brew "tmux"
brew "tnftp"
brew "tree"
brew "unison"
brew "vim"
brew "watch"
brew "hashicorp/tap/terraform"
brew "heroku/brew/heroku"
cask "aerial"
cask "font-hackgen"
cask "font-hackgen-nerd"
mas "1Password 7", id: 1333542190
mas "Magnet", id: 441258766
mas "LINE", id: 539883307
mas "Xcode", id: 497799835
