# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'maxpetretta/tmux-monokai-pro'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

#マウス操作を有効にする
set-option -g mouse on

# 色の設定
set-option -g default-terminal "screen-256color"

# マウスでコピーできるように
set-option -g mouse on
bind-key -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind-key -n WheelDownPane select-pane -t= \; send-keys -M

# コピーモードをvi風にする
setw -g mode-keys vi

# Windowの入れ替え
bind-key -n C-S-Left swap-window -t -1
bind-key -n C-S-Right swap-window -t +1

